query ExpertDashboardData {
    expertDashboardData {
        expertInquiryData {
            inquired,
            answered,
            rejected,
            open
        }
        expertAnswerData {
            answers,
            votes
        }
    }
}
