query QuestionData($includedTags: [String]!, $excludedTags: [String]!, $categoryCode: String, $dates: [String], $semanticTags: [String]) {
  questionsByEditorFilter(includedTags: $includedTags, excludedTags: $excludedTags, categoryCode: $categoryCode, dates: $dates, semanticTags: $semanticTags) {
       question {
        datastream {
            id
            name
            description
            category
            resultTime
            images
        }
       }
       observations {
           result
       }
       expertInquiry {
          created
          user {
              username
          }
          answered
          rejected
          comment
      }
  }
}
