query UnansweredQuestions($size: Int!) {
    unansweredQuestions (size: $size) {
       id
        votes {
            upCount
            downCount
        }
        datastream {
            name
            description
            resultTime
            images
            category
            observedArea
        }
        answers {
            id
            user {
                roles {
                    name
                }
            }
        }
    }
}
